language: java
env:
  global:
    - # ^^ OSSRH_USERNAME
    - secure: "gyV5MTIjA4N0EiErZnZfOADwkMCkq16MKV8v5tR3pEq7bB6MDWrwrpzCEUputQml4xfXi+LT4xIxchvaqAm7OfxSGh6bqN09fv/zCM/10VDnn46YTxle02j03PXDZ04/HByUHShQ5yWUWMZkOTwcjXppzV1lmIRbI1B5WQZfL9qoyulvVnxHVSgcZ1Lfq/DO8RMTi+9aYE1ptWkx5iBYY89OtWNzX0VPN/foDkETodDsOAEzCCuZiImIhDiFaTetxOd7QNkeP9AVjUoFWPFW9bTTN44ZLSmNMPKMUNiaobX5Af4KqhyBysj5Bc4iXNvKp58DgAUeB/QTZnhGcyLMaTXxdGZS0R6CNo5KRHOBx7B8FiFZrp0FOtJQcfX7iSE1Ut7P9LH4tQ1ODDzCvBJiixgPsMvUjSgoETgLcogrGvLy1cbENvQiahSkP16QVKCV28VhR94rfDrmAjXCQsDCE+pEzGmaS/bMbhAXFeHBwoNJuZJlYIbUBiis0LCZQMmJGjKjAnP9PGNjwHzCpiiEDftHh3rAGg3jowUkHeWjUIK03vKPOVLWkrBxM/4fKBF65Mfp+c2Qqxay29hIWgywD4nBqATdKHA0ur9yBx8TVHiNQSmpJLFwsJaDqq3Ek+WkOFLRQJ6d8gjKdcGslE/7UYQnaWsIKC/+Qpq+68P6OVU="
    - # ^^ OSSRH_PASSWORD
    - secure: "EXutDS0XyxpRZc2/kcyD2Ut9r2/b4ZCTArD3RBltN32OhUexJyeCufs2LejvPjfPhkSa/XJD12bqaTaT9KcGx96Y6Du1oUDObZTXLtNhZ6hwua0d0j7x1qt91AapeGxF0kMolpFn5cuQxSCcPuFOa2WZfQcwQWRXcqvrP26BSTVYhtASOip0+tHcboTEVkRLWkesMDpY/0mCAfYNVTzIDr7um3lSmiz0yBsyLhDI10QuAxUHc1GVDduv1JZ/ax+Sx83JGqVn52J6TclT2B8odnkm5PNXV5xiYWrM7Rav4HiSxW3GqTXKMaqP5HRt8Vu0SZU7HSc57d79s7ahVl1zF44ihQxxbnUvoA1B66DW251SoB9uIG6ZniCDFBXHaiINK6YuDL8YTkVDBrjo/3ljbBYdMZVuW+0K35tojdYw1wfG/MWEtP2V+3iW0mdGQDSxVPq1bKFiVSSpplNTNoPbHDaA7O20UiY9cBQVb4PsqXmWa4mUqp7frL3+BKJd5rwKuTKYG75aJDBOw6XTPONjV5Y+x0cEK4tInOO7xXvkbdTlA/d1ExaDB6CbQSVGZLAWmy/zS3JI+ri/Mct7AuiSsdZ5WYIBAThFuYpzjRxyMYwCoARERhU5P2IM+VDM2CWcEIKR5ouTJczyaC5Wj7Gn8A1DAf/itUZdzeF8dYAAv1c="
    - # ^^ GPG_KEY_NAME
    - secure: "bZ8oTWm3jl+PNKcDxnZCRvZ/b4E4b4A/vaxon2qvftgG+SFsg8AOI5nmqHCf5gJmzlzQr566k0ElIkdNfqOh6Kd3l35Fp/esHME+yxvPOkqvsXG3kYWKVx3t/bo5N4w+oJed0FBgsxbn/gfu+vY7cFy8ghPAmbltHAQdgkgRLXIT+e3c4mJOw8VOrqvcAFvIo0kBn17lrGj0SqDd+dPogaayb+B8/YER+wLcMYY6ViQ/ZBSynuxjj5XpApbRF7oGxWJHJFgzEOHZ6/jNhMhS7gNmPkdsTrLAdRLrOrGintPnXlTmi1OuPK/LFjEzPK40vOg4A64OeV7T9eXTdZExZocV6eYsAT/cy4QZNxVNbsuCEgVBSkQSVNaYgVAtnKG3m5F0hf+D+jVlR9dgA2KUHAk/0UWbJDk13YbHVNMmIflFRmBeySkJ/AWsRiIwXcYR+RWuteNMhSHZ4ZHor/mwv9KaeQGNHJMyMHM28DrbkIyOs7MODk/IsfXI8Q4M44oraiJrc1LmG1p1XYgHV94nGajsThKEPIfICR1QrHBDKbs8gNvzWMVvROv5MiDDWyoRfxeFLOQmyWrEHTmnSlj34EtvZO4w+DkTO/xyhCBWfAOFfbX1IY0DJtD1gpc/btIWJqIC84kmEbPjem+5idXNG5xZ1MzXMZGzVUCUK7RJ5AQ="
    - # ^^ GPG_PASSPHRASE
    - secure: "TlswIg1eB2IS/6ALc92Gg9eWxn8TFVO6iZ9zWUtkjNg/Rha929JZoEwrft3+K/ut4YHfnoXpVIGcmcRhZa5Vi/XLnO+g7osrJREsEYm0l9p6KGKRHMAHAQkH3SI5yg1OhVMBCnthhtIN3uiMcQc+nyJ9Ld96yPdxlDBDlCt1+Mb0LFPlCh94CVMGM+2iGK72IgaIBcJnmlwfvYHlhMQGbpNtlFsgrMe7ZYCTpWyqPrCoe2ToWGzXbFO39826IMTcfUVh+G8PlJJfInfoR+tIGm6Udu4T0SZ/6AbKFMIVeaXgQuVV8/SOmPOLiudy0tTBOeSOSLWijr+64AicjJrgW3SW1j/9MJuqskQDFx0wqSM0sPFA4Tz5Nbt7L00xFs19L0h8gHbfWXT2BOSYE9nktEepLmdFoMLuWwRwOMrErB46bGQ07V0bQjnN8NmYfSi8gBx6Q6PLtkFBwzsn+Tk/jB2M/VVrOgsUbpUFG4wmdlXSD/loURrXIk5lLGJHQGBdTgdKGEZEeNFFKjlKS6PADDWsxoHZsXxOknnH52UkcsXiJ+M2pRtklTwefDqGuRdXucvY/AXeAiORkdamq7akJUmguikBHzcmhCvDugkngJemDOUwsSj+Wb92aW73sBJljvfvonj1rVT9xkx15xgO4MrLbrg0NOXQKeg0BG8KgpE="
before_install:
  - openssl aes-256-cbc -K $encrypted_c91ff6812df7_key -iv $encrypted_c91ff6812df7_iv -in codesigning.asc.enc -out codesigning.asc -d
  - gpg --yes --batch --import codesigning.asc
jdk:
  - oraclejdk8
install: mvn clean install -P !ossrh -B -V -U
script:
- mvn deploy -P ossrh --settings mvnsettings.xml
cache:
  directories:
    - ~/.m2/repository
branches:
  only:
    - 6.3/master
    - 6.3/develop                                                            
notifications:
  email:
    on_success: change
    on_failure: change